### ISSUE TITLE
Logo Design: EasyShapeView

### ISSUE THREAD

**Issue by baranpirincal** [mkrupal09/EasyShapeView#1]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Baran Pirinçal

Graphic Designer

**Comment by mkrupal09** [comment]
Hello Sir,

Thank you so much for showing your interest. i've seen your past work i'm really impressed with your work. i've also worked as graphic designer but after seeing your work i thought i was nothing at design.

But sorry i don't have a plan for making logo of my project. but yes i've plan to make my logo as i made by hand drawn. you can see logo at my profile.

I'll happy if you can sharpen that logo. but please keep in mind that design, color shouldn't change only you need to make variant for it. i.e make solid logo or better.

thank you so much baran. 

let me know your thoughts.

Regards
Krupal Mehta

**Comment by mkrupal09** [comment]
![dclogo](https://user-images.githubusercontent.com/5485471/42634291-716d4a8e-8600-11e8-9ee5-55103fe4fef6.jpg)
